---
name: Presidio ğŸ§ª

on:
  push:
    branches:
      - main
      - pre-release
  pull_request:
    branches:
      - main
      - pre-release

jobs:
  presidio:
    name: Presidio ğŸ§ª
    runs-on: ubuntu-latest
    if: "! contains(github.event.commits[0].message, '[skip presidio]')"
    steps:
      - name: Checkout repo ğŸ›
        uses: actions/checkout@v2

      - name: Run Presidio â˜”
        uses: insightsengineering/presidio-action@beutify-msg
        with:
          output: "standard"
